#!/usr/bin/env bash

# fstr - substitute placeholders in strings
# copyright (c) 2025  Alex Rogers (https://github.com/linguisticmind)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

declare -- script_source=$(realpath -- "${BASH_SOURCE[0]}")
declare -- script_dir="$(dirname -- "$script_source")"

{ type -P lua5.4 || type -P lua; } &> /dev/null && "$_" "$script_dir"'/fstr.lua' "$@"
